server/config/routes.rb
Huntr::Application.routes.draw do
  get "quests/index"

  get "quests/show"
  
  get "js_api_key" => "users#js_api"

  get "login" => 'users#login', as: 'login'
  post 'login' => 'users#do_login'

  get "logout" => 'users#logout'
  
  match "register" => 'users#register'
  
  resources :quests
  
  # API
  namespace 'api' do
    get "login" => 'users#login'
    get "logout" => 'users#logout'
    get "register" => 'users#register'
    get "ping" => 'users#ping'
    resources :user_quests do
      resources :user_steps, as: 'steps'
    end
    resources :quests do
      resources :steps do
        get :next_seq, :on => :collection
      end
      resources :comments
      get 'nearby', :on => :collection
    end
  end

  root :to => "quests#index"

  # See how all your routes lay out with "rake routes"
end

server/app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
  has_many :quests, foreign_key: "created_by_id"
  has_many :user_quests
  has_many :comments
  
  attr_accessor :password
  
  validates_uniqueness_of :name, :email
  validates_presence_of :name, :email
  validates_confirmation_of :password  
  validates_presence_of :password, :on => :create
  
  before_save :encrypt_password
  
  def pass
    @pass ||= BCrypt::Password.new(password_hash) if password_hash.present?
  end
  
  def encrypt_password  
    if password.present?
      self.password_hash = BCrypt::Password.create(password)  
      self.password = nil
    end  
  end
end

server/app/controllers/api/users_controller.rb
require 'uuidtools'
class Api::UsersController < Api::ApplicationController
  skip_before_filter :require_user, only: [:login, :register]

  def login
    cred = params[:user] || {}
    user = User.find_by_name(cred[:name])
    if user and user.pass == cred[:password]
      send_token user
    else
      respond_with error: 'Invalid Username or Password'
    end
  end

  def ping
    respond_with "pong"
  end

  def logout
    @token.delete
    respond_with ''
  end
  
  def register
    if params[:user]
      regData = params[:user]
      regData[:password_confirmation] = regData[:password] # Skip Password Verification
    end
    user = User.new(regData)
    if user.save
      send_token user
    else
      respond_with({error: 'Could not create user.', validations: user.errors})
    end
  end

  private
  def send_token(user)
    token = AuthToken.create(user: user, token: UUIDTools::UUID.timestamp_create.to_s)
    token.save
    respond_with token: token.token
  end
end

server/app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :require_user, only: [:login, :do_login, :register]
  
  def login
  end
  
  def js_api
    token = AuthToken.create(user: @user, token: UUIDTools::UUID.timestamp_create.to_s)
    token.save
    respond_to do |format|
      object = {user: @user.name, key: token.token}
      format.json { render json: object }
    end
  end
  
  def do_login
    @user = User.find_by_name(params[:name])
    if @user and @user.pass == params[:password]
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Login Successful"
    else
      flash[:notice] = 'Invalid Username or Password'
      redirect_to login_url
    end
  end

  def logout
    session.delete :user_id
  end

  def register
    if request.post? and params[:user]
      @user = User.new(params[:user])
      
      if @user.save
        session[:user_id] = @user.id
        
        redirect_to root_url, notice: "User created."
      end
    else
      @user = User.new
    end
  end

end

server/app/helpers/user_helper.rb
module UserHelper
end

server/app/views/users/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

server/app/views/users/index.html.erb
<h1>User#show</h1>
<p>Find me in app/views/user/index.html.erb</p>

server/app/views/users/login.html.erb
<h1>Login</h1>
<%= flash[:notice] %>
<%= form_tag action: 'login' do %>

	<%= label_tag :name, "Username:" %>
	<%= text_field_tag :name %><br/>
	
	<%= label_tag :name, "Password:" %>
	<%= password_field_tag :password %><br/>

	<%= submit_tag "Login" %>
<% end %>

server/app/views/users/logout.html.erb
<h1>User#logout</h1>
<p>Find me in app/views/user/logout.html.erb</p>

server/app/views/users/register.html.erb
<% form_for @user, url: register_url do |f| %>
  <%= error_messages_for :user %>
 
  Username: <%= f.text_field :name %><br/>
  Email: <%= f.text_field :email %><br/>
  Password: <%= f.password_field :password %><br/>
  Confirm Password: <%= f.password_field :password_confirmation %><br/>
  <%= f.submit "Register"  %>
<% end %>